name: Simple Python Test CI

# Trigger this workflow on every push and pull request to any branch
on: [push, pull_request]

jobs:

  Build_Backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: docker build -t test .

  test:
    needs: Build_Backend
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # You can choose a specific Python version

      # Step 3: Install dependencies (just pytest for this simple case)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # Step 4: Run tests (this is the single command you wanted)
      - name: Run tests
        run: pytest test_main.py